StackUnderflow/config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  resources :question_votes
  resources :questions
  resources :answers
  resources :answer_votes
  resources :answer_comments

  root 'pages#index'

end

StackUnderflow/app/models/question_comment.rb
class QuestionComment < ActiveRecord::Base
  belongs_to :question
end

StackUnderflow/app/controllers/question_comments_controller.rb
class QuestionCommentsController < ApplicationController
  before_action :set_question_comment, only: [:show, :edit, :update, :destroy]

  # GET /question_comments
  # GET /question_comments.json
  def index
    @question_comments = QuestionComment.all
  end

  # GET /question_comments/1
  # GET /question_comments/1.json
  def show
  end

  # GET /question_comments/new
  def new
    @question_comment = QuestionComment.new
  end

  # GET /question_comments/1/edit
  def edit
  end

  # POST /question_comments
  # POST /question_comments.json
  def create
    @question_comment = QuestionComment.new(question_comment_params)

    respond_to do |format|
      if @question_comment.save
        format.html { redirect_to @question_comment, notice: 'Question comment was successfully created.' }
        format.json { render :show, status: :created, location: @question_comment }
      else
        format.html { render :new }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_comments/1
  # PATCH/PUT /question_comments/1.json
  def update
    respond_to do |format|
      if @question_comment.update(question_comment_params)
        format.html { redirect_to @question_comment, notice: 'Question comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_comment }
      else
        format.html { render :edit }
        format.json { render json: @question_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_comments/1
  # DELETE /question_comments/1.json
  def destroy
    @question_comment.destroy
    respond_to do |format|
      format.html { redirect_to question_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_comment
      @question_comment = QuestionComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_comment_params
      params.require(:question_comment).permit(:question_id, :user_id, :content)
    end
end

StackUnderflow/app/helpers/question_comments_helper.rb
module QuestionCommentsHelper
end

StackUnderflow/app/views/question_comments/_form.html.erb
<%= form_for(@question_comment) do |f| %>
  <% if @question_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_comment.errors.count, "error") %> prohibited this question_comment from being saved:</h2>

      <ul>
      <% @question_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StackUnderflow/app/views/question_comments/edit.html.erb
<h1>Editing question_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_comment %> |
<%= link_to 'Back', question_comments_path %>

StackUnderflow/app/views/question_comments/index.html.erb
<h1>Listing question_comments</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_comments.each do |question_comment| %>
      <tr>
        <td><%= question_comment.question_id %></td>
        <td><%= question_comment.user_id %></td>
        <td><%= question_comment.content %></td>
        <td><%= link_to 'Show', question_comment %></td>
        <td><%= link_to 'Edit', edit_question_comment_path(question_comment) %></td>
        <td><%= link_to 'Destroy', question_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question comment', new_question_comment_path %>

StackUnderflow/app/views/question_comments/new.html.erb
<h1>New question_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', question_comments_path %>

StackUnderflow/app/views/question_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_comment.question_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @question_comment.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question_comment.content %>
</p>

<%= link_to 'Edit', edit_question_comment_path(@question_comment) %> |
<%= link_to 'Back', question_comments_path %>