StackUnderflow/config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  resources :question_votes
  resources :questions
  resources :answers
  resources :answer_votes
  resources :answer_comments

  root 'pages#index'

end

StackUnderflow/app/models/answer_comment.rb
class AnswerComment < ActiveRecord::Base
  belongs_to :answer
end

StackUnderflow/app/controllers/answer_comments_controller.rb
class AnswerCommentsController < ApplicationController
  before_action :set_answer_comment, only: [:show, :edit, :update, :destroy]

  # GET /answer_comments
  # GET /answer_comments.json
  def index
    @answer_comments = AnswerComment.all
  end

  # GET /answer_comments/1
  # GET /answer_comments/1.json
  def show
  end

  # GET /answer_comments/new
  def new
    @answer_comment = AnswerComment.new
  end

  # GET /answer_comments/1/edit
  def edit
  end

  # POST /answer_comments
  # POST /answer_comments.json
  def create
    @answer_comment = AnswerComment.new(answer_comment_params)

    respond_to do |format|
      if @answer_comment.save
        format.html { redirect_to @answer_comment, notice: 'Answer comment was successfully created.' }
        format.json { render :show, status: :created, location: @answer_comment }
      else
        format.html { render :new }
        format.json { render json: @answer_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_comments/1
  # PATCH/PUT /answer_comments/1.json
  def update
    respond_to do |format|
      if @answer_comment.update(answer_comment_params)
        format.html { redirect_to @answer_comment, notice: 'Answer comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer_comment }
      else
        format.html { render :edit }
        format.json { render json: @answer_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_comments/1
  # DELETE /answer_comments/1.json
  def destroy
    @answer_comment.destroy
    respond_to do |format|
      format.html { redirect_to answer_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_comment
      @answer_comment = AnswerComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_comment_params
      params.require(:answer_comment).permit(:content, :user_id, :answer_id)
    end
end

StackUnderflow/app/helpers/answer_comments_helper.rb
module AnswerCommentsHelper
end

StackUnderflow/app/views/answer_comments/_form.html.erb
<%= form_for(@answer_comment) do |f| %>
  <% if @answer_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_comment.errors.count, "error") %> prohibited this answer_comment from being saved:</h2>

      <ul>
      <% @answer_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
<%= f.label :content %><br />
<%= f.text_field :content %>
</p>

<p>
<%= f.label :user_id %><br />
<%= f.number_field :user_id %>
</p>

<p>
<%= f.label :answer_id %><br />
<%= f.number_field :answer_id %>
</p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StackUnderflow/app/views/answer_comments/edit.html.erb
<h1>Editing answer_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_comment %> |
<%= link_to 'Back', answer_comments_path %>

StackUnderflow/app/views/answer_comments/index.html.erb
<h1>Listing answer_comments</h1>

<table>
  <thead>
    <tr>
      <th>content</th>
      <th>user_id</th>
      <th>answer_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_comments.each do |answer_comment| %>
      <tr>
        <td><%= answer_comment.content %></td>
        <td><%= answer_comment.user_id %></td>
        <td><%= answer_comment.answer_id %></td>
	</tr>
	<tr>
        <td><%= link_to 'Show', answer_comment %></td>
        <td><%= link_to 'Edit', edit_answer_comment_path(answer_comment) %></td>
        <td><%= link_to 'Destroy', answer_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer comment', new_answer_comment_path %>

StackUnderflow/app/views/answer_comments/new.html.erb
<h1>New answer_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_comments_path %>

StackUnderflow/app/views/answer_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<b>Content: </b><br />
<%= @answer_comment.content %>
</p>

<p>
<b>User ID: </b><br />
<%= @answer_comment.user_id %>
</p>

<p>
<b>Answer ID: </b><br />
<%= @answer_comment.answer_id %>
</p>

<%= link_to 'Edit', edit_answer_comment_path(@answer_comment) %> |
<%= link_to 'Back', answer_comments_path %>