StackUnderflow/config/routes.rb
Rails.application.routes.draw do
  resources :question_comments
  resources :question_votes
  resources :questions
  resources :answers
  resources :answer_votes
  resources :answer_comments

  root 'pages#index'

end

StackUnderflow/app/models/answer_vote.rb
class AnswerVote < ActiveRecord::Base
  belongs_to :answer
end

StackUnderflow/app/controllers/answer_votes_controller.rb
class AnswerVotesController < ApplicationController
  before_action :set_answer_vote, only: [:show, :edit, :update, :destroy]

  # GET /answer_votes
  # GET /answer_votes.json
  def index
    @answer_votes = AnswerVote.all
  end

  # GET /answer_votes/1
  # GET /answer_votes/1.json
  def show
  end

  # GET /answer_votes/new
  def new
    @answer_vote = AnswerVote.new
  end

  # GET /answer_votes/1/edit
  def edit
  end

  # POST /answer_votes
  # POST /answer_votes.json
  def create
    @answer_vote = AnswerVote.new(answer_vote_params)

    respond_to do |format|
      if @answer_vote.save
        format.html { redirect_to @answer_vote, notice: 'Answer vote was successfully created.' }
        format.json { render :show, status: :created, location: @answer_vote }
      else
        format.html { render :new }
        format.json { render json: @answer_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_votes/1
  # PATCH/PUT /answer_votes/1.json
  def update
    respond_to do |format|
      if @answer_vote.update(answer_vote_params)
        format.html { redirect_to @answer_vote, notice: 'Answer vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer_vote }
      else
        format.html { render :edit }
        format.json { render json: @answer_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_votes/1
  # DELETE /answer_votes/1.json
  def destroy
    @answer_vote.destroy
    respond_to do |format|
      format.html { redirect_to answer_votes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_vote
      @answer_vote = AnswerVote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_vote_params
      params.require(:answer_vote).permit(:value, :user_id, :answer_id)
    end
end

StackUnderflow/app/helpers/answer_votes_helper.rb
module AnswerVotesHelper
end

StackUnderflow/app/views/answer_votes/_form.html.erb
<%= form_for(@answer_vote) do |f| %>
  <% if @answer_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_vote.errors.count, "error") %> prohibited this answer_vote from being saved:</h2>

      <ul>
      <% @answer_vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

StackUnderflow/app/views/answer_votes/edit.html.erb
<h1>Editing answer_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_vote %> |
<%= link_to 'Back', answer_votes_path %>

StackUnderflow/app/views/answer_votes/index.html.erb
<h1>Listing answer_votes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_votes.each do |answer_vote| %>
      <tr>
        <td><%= link_to 'Show', answer_vote %></td>
        <td><%= link_to 'Edit', edit_answer_vote_path(answer_vote) %></td>
        <td><%= link_to 'Destroy', answer_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer vote', new_answer_vote_path %>

StackUnderflow/app/views/answer_votes/new.html.erb
<h1>New answer_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_votes_path %>

StackUnderflow/app/views/answer_votes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_answer_vote_path(@answer_vote) %> |
<%= link_to 'Back', answer_votes_path %>